src/Entity/Objectif.php
<?php

namespace App\Entity;
use Symfony\Component\Validator\Constraints as Assert;


use App\Repository\ObjectifRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ObjectifRepository::class)]
class Objectif
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column (nullable : true)]
    private ?int $id = null;

    #[ORM\Column]
    #[Assert\NotBlank(message: "Veuillez entrer un poids désiré")]
    /**

     * @Assert\Type(type="numeric")
     * @Assert\GreaterThan(value=0, message="On peut pas mettre 0")
     */

    private ?int $PoidsDes = null;

    #[ORM\Column]
    #[Assert\NotBlank(message: "Veuillez choisir le type de votre régime")]
    /**

     * @Assert\Type(type="numeric")
     * @Assert\Choice(choices={2, 1})

     */

    private ?int $TypeReg = null;

    #[ORM\Column]
    #[Assert\NotBlank(message: "Veuillez rentrer le nombre de calories recommandés")]
    /**

     * @Assert\Type(type="numeric")
     * @Assert\GreaterThan(value=0, message="On peut pas mettre 0")
     */

    private ?int $CalCons = null;

    #[ORM\OneToMany(mappedBy: 'objectif', targetEntity: Routine::class)]
    private Collection $routines;




    #[ORM\Column(nullable: true)]
    #[Assert\NotBlank(message: "Veuillez entrer votre age")]
    /**

     * @Assert\Type(type="numeric")
     * @Assert\GreaterThan(value=0, message="On peut pas mettre 0")
     */
    private ?int $Age = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank(message: "Veuillez choisir le type de votre régime")]
    /**

     * @Assert\Type(type="string")
     * @Assert\Choice(choices={"M","F"})

     */

    private ?string $Sexe = null;

    #[ORM\Column(nullable: true)]
    #[Assert\NotBlank(message: "Veuillez entrer un poids actuelle")]
    /**

     * @Assert\Type(type="numeric")
     * @Assert\GreaterThan(value=0, message="On peut pas mettre 0")
     */
    private ?int $Poids = null;

    #[ORM\Column(nullable: true)]
    #[Assert\NotBlank(message: "Veuillez entrer votre taille")]
    /**

     * @Assert\Type(type="numeric")
     * @Assert\GreaterThan(value=0, message="On peut pas mettre 0")
     */
    private ?int $taille = null;




    public function __construct()
    {
        $this->routines = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPoidsDes(): ?int
    {
        return $this->PoidsDes;
    }

    public function setPoidsDes(int $PoidsDes): self
    {
        $this->PoidsDes = $PoidsDes;

        return $this;
    }

    public function getTypeReg(): ?int
    {
        return $this->TypeReg;
    }

    public function setTypeReg(int $TypeReg): self
    {
        $this->TypeReg = $TypeReg;

        return $this;
    }

    public function getCalCons(): ?int
    {
        return $this->CalCons;
    }

    public function setCalCons(int $CalCons): self
    {
        $this->CalCons = $CalCons;

        return $this;
    }

    /**
     * @return Collection<int, Routine>
     */
    public function getRoutines(): Collection
    {
        return $this->routines;
    }

    public function addRoutine(Routine $routine): self
    {
        if (!$this->routines->contains($routine)) {
            $this->routines->add($routine);
            $routine->setObjectif($this);
        }

        return $this;
    }

    public function removeRoutine(Routine $routine): self
    {
        if ($this->routines->removeElement($routine)) {
            // set the owning side to null (unless already changed)
            if ($routine->getObjectif() === $this) {
                $routine->setObjectif(null);
            }
        }

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->Age;
    }

    public function setAge(?int $Age): self
    {
        $this->Age = $Age;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->Sexe;
    }

    public function setSexe(?string $Sexe): self
    {
        $this->Sexe = $Sexe;

        return $this;
    }

    public function getPoids(): ?int
    {
        return $this->Poids;
    }

    public function setPoids(?int $Poids): self
    {
        $this->Poids = $Poids;

        return $this;
    }

    public function getTaille(): ?int
    {
        return $this->taille;
    }

    public function setTaille(?int $taille): self
    {
        $this->taille = $taille;

        return $this;
    }



   





}

src/Entity/Routine.php
<?php

namespace App\Entity;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Constraints as Assert;


use App\Repository\RoutineRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\Nullable;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: RoutineRepository::class)]
class Routine
{
    #[ORM\Id]
    #[ORM\GeneratedValue    ]
    #[ORM\Column]
    /**
     * @Groups ("routinee")
     */


    private ?int $id = null;


    #[ORM\ManyToOne(cascade:  ["persist"], inversedBy: 'routinesDejeuner')]
    #[Assert\NotBlank(message: "Veuillez Séléctionner un aliment")]
    /**
     * @Groups ("routinee")
     *
     */

    private ?Aliment $Dejeuner = null;


    #[ORM\Column]
    #[Assert\NotBlank(message: "Veuillez remplir les calories consommés")]
    /**
     * @Groups ("routinee")
     */
    private ?int $CalCons = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]

    #[Assert\GreaterThan("today", message:"Date must not be in the past.")]
    /**
     * @Groups ("routinee")
     */
    private ?\DateTimeInterface $Date = null;

    #[ORM\ManyToOne(cascade: ["persist"],inversedBy: 'routines')]
    #[ORM\JoinColumn(nullable: true)]
    /**
     * @Groups ("routinee")
     */
    private ?Aliment $aliments = null;



    #[ORM\ManyToOne(cascade:  ["persist"],inversedBy: 'routines')]
    #[ORM\JoinColumn(nullable: false)]
    /**
     * @Groups ("routinee")
     */
    private ?Objectif $objectif = null;

    #[ORM\ManyToOne(cascade:  ["persist"],inversedBy: 'routinesMidi')]
    #[Assert\NotBlank(message: "Veuillez Séléctionner un aliment")]
    /**
     * @Groups ("routinee")
     */
    private ?Aliment $Midi = null;

    #[ORM\ManyToOne(cascade: ["persist"],inversedBy: 'routinesDinner')]
    #[Assert\NotBlank(message: "Veuillez Séléctionner un aliment")]
    /**
     * @Groups ("routinee")
     */

    private ?Aliment $Dinner = null;

    #[ORM\ManyToMany(cascade:  ["persist"],targetEntity: Aliment::class, inversedBy: 'routiness')]

    private Collection $alimentss;

    public function __construct()
    {
        $this->alimentss = new ArrayCollection();
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDej(): ?string
    {
        return $this->Dej;
    }

    public function setDej(string $Dej): self
    {
        $this->Dej = $Dej;

        return $this;
    }






    public function getCalCons(): ?int
    {
        return $this->CalCons;
    }

    public function setCalCons(int $CalCons): self
    {
        $this->CalCons = $CalCons;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    public function getAliments(): ?Aliment
    {
        return $this->aliments;
    }

    public function setAliments(?Aliment $aliments): self
    {
        $this->aliments = $aliments;

        return $this;
    }

    public function getObjectif(): ?Objectif
    {
        return $this->objectif;
    }

    public function setObjectif(?Objectif $objectif): self
    {
        $this->objectif = $objectif;

        return $this;
    }

    public function getDejeuner(): ?Aliment
    {
        return $this->Dejeuner;
    }

    public function setDejeuner(?Aliment $Dejeuner): self
    {
        $this->Dejeuner = $Dejeuner;

        return $this;
    }

    public function getMidi(): ?Aliment
    {
        return $this->Midi;
    }

    public function setMidi(?Aliment $Midi): self
    {
        $this->Midi = $Midi;

        return $this;
    }

    public function getDinner(): ?Aliment
    {
        return $this->Dinner;
    }

    public function setDinner(?Aliment $Dinner): self
    {
        $this->Dinner = $Dinner;

        return $this;
    }

    /**
     * @return Collection<int, Aliment>
     */
    public function getAlimentss(): Collection
    {
        return $this->alimentss;
    }

    public function addAlimentss(Aliment $alimentss): self
    {
        if (!$this->alimentss->contains($alimentss)) {
            $this->alimentss->add($alimentss);
        }

        return $this;
    }

    public function removeAlimentss(Aliment $alimentss): self
    {
        $this->alimentss->removeElement($alimentss);

        return $this;
    }
}

src/Controller/ObjectifController.php
<?php

namespace App\Controller;

use App\Entity\Objectif;
use App\Form\Objectif1Type;
use App\Form\ObjectifFront;
use App\Repository\ObjectifRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/objectif')]
class ObjectifController extends AbstractController
{
    #[Route('/', name: 'app_objectif_index', methods: ['GET'])]
    public function index(ObjectifRepository $objectifRepository): Response
    {
        return $this->render('objectif/index.html.twig', [
            'objectifs' => $objectifRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_objectif_newB', methods: ['GET', 'POST'])]
    public function new(Request $request, ObjectifRepository $objectifRepository): Response
    {
        $objectif = new Objectif();

        $form = $this->createForm(Objectif1Type::class, $objectif);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {


            $objectifRepository->save($objectif, true);

            return $this->redirectToRoute('app_objectif_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('objectif/new.html.twig', [
            'objectif' => $objectif,
            'form' => $form,
        ]);
    }


    #[Route('/newObjFront', name: 'app_objectif_new', methods: ['GET', 'POST'])]
    public function NewFront(Request $request, ObjectifRepository $objectifRepository): Response
    {
        $objectif = new Objectif();
        $form = $this->createForm(ObjectifFront::class, $objectif);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $a = $form->get('Age')->getData();

            $s = $form->get('Sexe')->getData();
            $type = $form->get('TypeReg')->getData();
            $poids = $form->get('Poids')->getData();
            $t = $form->get('Taille')->getData();

            if ($type==1){
                if ($s=='M'){
                    $calorie=($poids*13.4)+(4.8*$t)+($a*5.7)+ 88.36-600;
                }else
                    $calorie=($poids*9.2)+(3.1*$t)+($a*4.3)+ 447.6-600;
            } else {
                if ($s=='M'){
                    $calorie=($poids*13.4)+(4.8*$t)+($a*5.7)+ 88.36+600;
                }else
                    $calorie=($poids*9.2)+(3.1*$t)+($a*4.3)+ 447.6+600;
            }

            $objectif->setCalCons($calorie);

            $objectifRepository->save($objectif, true);

        }
        return $this->renderForm('objectif/FrontObjectif.html.twig', [
            'objectif' => $objectif,
            'form' => $form,

        ]);
    }

    #[Route('/{id}', name: 'app_objectif_show', methods: ['GET'])]
    public function show(Objectif $objectif): Response
    {
        return $this->render('objectif/show.html.twig', [
            'objectif' => $objectif,

        ]);
    }

    #[Route('/{id}/edit', name: 'app_objectif_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Objectif $objectif, ObjectifRepository $objectifRepository): Response
    {
        $form = $this->createForm(Objectif1Type::class, $objectif);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $objectifRepository->save($objectif, true);

            return $this->redirectToRoute('app_objectif_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('objectif/edit.html.twig', [
            'objectif' => $objectif,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_objectif_delete', methods: ['POST'])]
    public function delete(Request $request, Objectif $objectif, ObjectifRepository $objectifRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$objectif->getId(), $request->request->get('_token'))) {
            $objectifRepository->remove($objectif, true);
        }

        return $this->redirectToRoute('app_objectif_index', [], Response::HTTP_SEE_OTHER);
    }







}

templates/objectif/FrontObjectif.html.twig
{% extends 'baseFront.html.twig' %}

{% block title %}New Routine{% endblock %}

{% block body %}
    <style>
        #evenement_date_month{
            border: 1px solid #d1d3e2;
            width: 150px;
            border-radius: 5px;
        }

        #evenement_date_day{
            border: 1px solid #d1d3e2;
            width: 150px;
            border-radius: 5px;
        }

        #evenement_date_year{
            border: 1px solid #d1d3e2;
            width: 150px;
            border-radius: 5px;
        }

        #evenement_date{
            border : transparent;
        }

    </style>

    <div class="container">

        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                    <div class="col-lg-12">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">Create a objectif!</h1>
                            </div>
                            {{form_start(form,{'attr':{'novalidate':'novalidate' , 'class' : 'user' }})}}


                            <div class="form-group row">

                                <div class="col-sm-3">

                                    {% if form_errors(form.PoidsDes) is not empty %}
                                        <div class="alert alert-danger" >
                                            {{ form_errors(form.PoidsDes) }}
                                        </div>
                                    {% endif %}
                                    {{ form_widget(form.PoidsDes,{ 'attr': {'class': 'form-control ',
                                        'name': 'dd', 'placeholder' : 'PoidsDes'} }) }}
                                </div>

                                <div class="col-sm-3">
                                    {% if form_errors(form.TypeReg) is not empty %}
                                        <div class="alert alert-danger" >
                                            {{ form_errors(form.TypeReg) }}
                                        </div>
                                    {% endif %}
                                    {{ form_widget(form.TypeReg,{ 'attr': {'class': 'form-control  ',
                                        'name': 'mm', 'placeholder' : 'TypeReg'} }) }}
                                </div>





                                <div class="col-sm-3">
                                    {% if form_errors(form.Age) is not empty %}
                                        <div class="alert alert-danger" >
                                            {{ form_errors(form.Age) }}
                                        </div>
                                    {% endif %}
                                    {{ form_widget(form.Age,{ 'attr': {'class': 'form-control  ',
                                        'name': 'nn', 'placeholder' : 'Age'} }) }}
                                </div>







                                <div class="col-sm-3">
                                    {% if form_errors(form.Sexe) is not empty %}
                                        <div class="alert alert-danger" >
                                            {{ form_errors(form.Sexe) }}
                                        </div>
                                    {% endif %}
                                    {{ form_widget(form.Sexe,{ 'attr': {'class': 'form-control  '  , 'placeholder' : 'Sexe' } }) }}
                                </div>

                                <div class="col-sm-3">
                                    {% if form_errors(form.Poids) is not empty %}
                                        <div class="alert alert-danger" >
                                            {{ form_errors(form.Poids) }}
                                        </div>
                                    {% endif %}
                                    {{ form_widget(form.Poids,{ 'attr': {'class': 'form-control  '  , 'placeholder' : 'Poids actuel' } }) }}
                                </div>

                                <div class="col-sm-3">
                                    {% if form_errors(form.Taille) is not empty %}
                                        <div class="alert alert-danger" >
                                            {{ form_errors(form.Taille) }}
                                        </div>
                                    {% endif %}
                                    {{ form_widget(form.Taille,{ 'attr': {'class': 'form-control  '  , 'placeholder' : 'Taille' } }) }}
                                </div>


                            </div>



                            <button class="btn btn-primary btn-user btn-block">{{ button_label|default('Save') }}</button>

                            {# <a href="login.html" class="btn btn-primary btn-user btn-block">
                                    Register Account
                                </a> #}
                            <hr>

                            {{ form_end(form) }}
                            <hr>
                            <div class="text-center">
                                <a href="{{ path('app_routine_index') }}">back to list</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>

{% endblock %}

templates/objectif/_delete_form.html.twig
<form method="post" action="{{ path('app_objectif_delete', {'id': objectif.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ objectif.id) }}">
    <button class="btn">Delete</button>
</form>

templates/objectif/_form.html.twig
{{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
    {{ form_widget(form) }}
<button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/objectif/edit.html.twig
{% extends 'admin/dashboardAdmin.html.twig' %}

{% block admin %}
    <h1>Edit Objectif</h1>

    {{ include('objectif/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_objectif_index') }}">back to list</a>

    {{ include('objectif/_delete_form.html.twig') }}
{% endblock %}

templates/objectif/index.html.twig
{% extends 'admin/dashboardAdmin.html.twig' %}

{% block admin %}

    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Tables</h1>
        <div style="display :flex;">
            <div class="col-lg-10">
                <p class="mb-4">DataTables is a third party plugin that is used to generate the demo table below.
                    For more information about DataTables, please visit the <a target="_blank"
                                                                               href="https://datatables.net">official DataTables documentation</a>.</p>
            </div>

            <div class="col-lg-2">
                <a style ="justify-content: center;display: inline-flex;width: 135px!important;height:
                                35px;background-color: #4c71de;color: white;padding-top: 5px;border-radius: 10px;"
                   href="{{ path('app_objectif_newB') }}">Create new</a>
            </div>
        </div>
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>id</th>
                            <th>PoidsDes</th>
                            <th>TypeReg</th>
                            <th>CalCons</th>
                            <th>Age</th>
                            <th>Sexe</th>
                            <th>Poids</th>
                            <th>Taille</th>





                            <th>actions</th>
                        </tr>
                        </thead>
                        <tbody>

                        {% for objectif in objectifs %}
                            <tr>
                                <td>{{ objectif.id }}</td>
                                <td>{{ objectif.PoidsDes }}</td>
                                <td>{{ objectif.TypeReg }}</td>
                                <td>{{ objectif.CalCons }}</td>
                                <td>{{ objectif.Age }}</td>
                                <td>{{ objectif.Sexe }}</td>
                                <td>{{ objectif.Poids }}</td>
                                <td>{{ objectif.Taille }}</td>




                                <td style="display: flex;" >
                                    <a style="justify-content: center;
    display: inline-flex;
    width: 90px!important;
    height: 35px;
    background-color: #4c71de;
    color: white;
    padding-top: 5px;
    border-radius: 10px;
    margin: 0px 3px 0px 3px;" href="{{ path('app_objectif_show', {'id': objectif.id}) }}">show</a>

                                    <a style="justify-content: center;
    display: inline-flex;
    width: 90px!important;
    height: 35px;
    background-color: #4c71de;
    color: white;
    padding-top: 5px;
    border-radius: 10px;
    margin: 0px 3px 0px 3px;"  href="{{ path('app_objectif_edit', {'id': objectif.id}) }}">edit</a>


                                    <form style="width: 4px;margin: 0px 3px 0px 3px; " method="post" action="{{ path('app_objectif_delete', {'id': objectif.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
                                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ objectif.id) }}">
                                        <button style="justify-content: center;
    display: inline-flex;
    width: 90px!important;
    height: 35px;
    background-color: #fd3838;
    color: white;
    padding-top: 5px;
    border-radius: 10px;"  class="btn">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        {% else %}
                            <tr>
                                <td colspan="6">no records found</td>
                            </tr>
                        {% endfor %}


                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->



    {# <h1>Evenement index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Type</th>
                <th>Date</th>
                <th>Adresse</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for evenement in evenements %}
            <tr>
                <td>{{ evenement.id }}</td>
                <td>{{ evenement.nom }}</td>
                <td>{{ evenement.type }}</td>
                <td>{{ evenement.date ? evenement.date|date('Y-m-d') : '' }}</td>
                <td>{{ evenement.adresse }}</td>
                <td>
                    <a href="{{ path('app_evenement_show', {'id': evenement.id}) }}">show</a>
                    <a href="{{ path('app_evenement_edit', {'id': evenement.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table> #}

{% endblock %}

templates/objectif/new.html.twig
{% extends 'admin/dashboardAdmin.html.twig' %}

{% block admin %}
    <style>
        #evenement_date_month{
            border: 1px solid #d1d3e2;
            width: 150px;
            border-radius: 5px;
        }

        #evenement_date_day{
            border: 1px solid #d1d3e2;
            width: 150px;
            border-radius: 5px;
        }

        #evenement_date_year{
            border: 1px solid #d1d3e2;
            width: 150px;
            border-radius: 5px;
        }

        #evenement_date{
            border : transparent;
        }

    </style>

    <div class="container">

        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                    <div class="col-lg-12">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">Create an Objectif!</h1>
                            </div>
                            {{form_start(form,{'attr':{'novalidate':'novalidate' , 'class' : 'user' }})}}

                            <div class="form-group row">
                                <div class="col-sm-6 mb-3 mb-sm-0">
                                    {% if form_errors(form.PoidsDes) is not empty %}
                                        <div class="alert alert-danger" >
                                            {{ form_errors(form.PoidsDes) }}
                                        </div>
                                    {% endif %}
                                    {{ form_widget(form.PoidsDes,{ 'attr': {'class': 'form-control form-control-user' , 'placeholder' : 'PoidsDes' } }) }}
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-sm-6 mb-3 mb-sm-0">
                                    {% if form_errors(form.CalCons) is not empty %}
                                        <div class="alert alert-danger" >
                                            {{ form_errors(form.CalCons) }}
                                        </div>
                                    {% endif %}
                                    {{ form_widget(form.CalCons,{ 'attr': {'class': 'form-control form-control-user' , 'placeholder' : 'Calorie Recommandé' } }) }}
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-sm-6 mb-3 mb-sm-0">
                                    {% if form_errors(form.TypeReg) is not empty %}
                                        <div class="alert alert-danger" >
                                            {{ form_errors(form.TypeReg) }}
                                        </div>
                                    {% endif %}
                                    {{ form_widget(form.TypeReg,{ 'attr': {'class': 'form-control form-control-user' , 'placeholder' : 'TypeReg' } }) }}
                                </div>
                                Mettez 1 pour diminuer le poids et 2 pour l'augmentation

                                <div class="col-sm-3">
                                    {% if form_errors(form.Age) is not empty %}
                                        <div class="alert alert-danger" >
                                            {{ form_errors(form.Age) }}
                                        </div>
                                    {% endif %}
                                    {{ form_widget(form.Age,{ 'attr': {'class': 'form-control form-control-user' , 'placeholder' : 'Age' } }) }}
                                </div>

                                <div class="col-sm-3">
                                    {% if form_errors(form.Sexe) is not empty %}
                                        <div class="alert alert-danger" >
                                            {{ form_errors(form.Sexe) }}
                                        </div>
                                    {% endif %}
                                    {{ form_widget(form.Sexe,{ 'attr': {'class': 'form-control form-control-user' , 'placeholder' : 'Sexe' } }) }}
                                </div>

                                <div class="col-sm-3">
                                    {% if form_errors(form.Poids) is not empty %}
                                        <div class="alert alert-danger" >
                                            {{ form_errors(form.Poids) }}
                                        </div>
                                    {% endif %}
                                    {{ form_widget(form.Poids,{ 'attr': {'class': 'form-control form-control-user' , 'placeholder' : 'Poids' } }) }}
                                </div>

                                <div class="col-sm-3">
                                    {% if form_errors(form.Taille) is not empty %}
                                        <div class="alert alert-danger" >
                                            {{ form_errors(form.Taille) }}
                                        </div>
                                    {% endif %}
                                    {{ form_widget(form.Taille,{ 'attr': {'class': 'form-control form-control-user' , 'placeholder' : 'Taille' } }) }}
                                </div>

                            </div>

                        </div>











                            {# <a href="login.html" class="btn btn-primary btn-user btn-block">
                                    Register Account
                                </a> #}
                            <button class="btn btn-primary btn-user btn-block">{{ button_label|default('Save') }}</button>

                            <hr>

                            {{ form_end(form) }}
                            <hr>
                            <div class="text-center">
                                <a href="{{ path('app_objectif_index') }}">back to list</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>

{% endblock %}